---
resources:
  - ../base
namespace: vm-pvc
commonLabels:
  app: vm-pvc
patches:
  - target:
      kind: Subscription
      name: subscription
    patch: |-
      - op: replace
        path: /metadata/annotations/apps.open-cluster-management.io~1github-path
        value: demo-vm1/primary
  - patch: |-
      apiVersion: cluster.open-cluster-management.io/v1beta1
      kind: Placement
      metadata:
        name: placement
      spec:
        clusterSets:
          - default
        numberOfClusters: 1
        predicates:
          - requiredClusterSelector:
              labelSelector:
                matchLabels:
                  csm-dr-scope: primary

