---
resources:
  - ../base
namespace: vm-pvc
commonLabels:
  app: vm-pvc
patches:
  - target:
      kind: Subscription
      name: subscription
    patch: |-
      - op: replace
        path: /metadata/annotations/apps.open-cluster-management.io~1github-path
        value: demo-vm1/secondary
  - target:
      kind: Placement
      name: placement
      path: placement.yaml

