apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "demovm-vol"
spec:
  source:
    http:
      url: "https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img" # S3 or GCS
  pvc:
    storageClassName: rep-src
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "64Mi"
