apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

patches:
  - patch: |
      - op: replace
        path: /spec/running
        value: false
    target:
      kind: VirtualMachine
resources:
  - datavolume.yaml
